Adding docker image workflow
rode/rode-ui pull request #9
Opened 2021-02-22 21:06 UTC by steeeveo

* Created dockerfile/dockerignore for UI
* Created build and publish workflow for UI

2021-02-22 21:07 UTC, pickjasmine submitted a review, later dismissed

2021-02-23 16:30 UTC, mrparkers requested changes

2021-02-23 17:37 UTC, steeeveo commented on .dockerignore
> +yarn-error.log*
Makes sense. Wouldn't this logic apply to `.gitignore` as well?

2021-02-25 22:06 UTC, mrparkers approved these changes

2021-02-25 22:09 UTC, merged